### ISSUE TITLE
TODO list thetvdb v2 API

### ISSUE THREAD

**Issue by p0psicles** [pymedusa/tvdbv2#1]
I'll use issue for discussion and as main TODO list for the tvdbv2 API.
The tvdbv2 api is still in beta, and often it's not accessible. I've created this report as a starting point, which we can use (or not) when the thetvdb v2 api is ready for production.

This is purely meant as the API's client code. We still need to write indexers code. But because we've already separated the tvmaze lib and indexer code, this wont be allot of work when the API is stable.

TODO:
- [x] Replace urllib3 with requests
- [ ] Remove the id vars
- [x] Create wrappers for initializing the Api
- [x] Create logic for refreshing the bearer token
- [x] Make it work. Because now, you can do requests, but results are all None
- [x] Create install.py package.

**Comment by p0psicles** [comment]
@labrys, maybe a good idea for you to also start looking at this. Better if detect issues early.

**Comment by p0psicles** [comment]
@pymedusa/developers Guys, if we want to make steps in using the new api as default for tvdb indexing, i'll need to have some feedback. Are we going to use this? Or are we going to use another lib? I"d like to have your opinions before I start implementing this.

**Comment by labrys** [comment]
@p0psicles I've begun looking into it but haven't had a lot of time to give it the attention it needs yet.

**Comment by p0psicles** [comment]
Yeah I understand. Np. But if we put some time into this. I can continue on doing some refactoring on the indexer code. backporting some tvmaze code, and separating medusa indexer and lib indexer code. So in other words, we can use tvdb api v2 to implement some of the tvmaze improvements. And also take some steps towards tvmaze indexer support.
